template = templates/jee1/glassfish-eclipse/settings/war/org.eclipse.wst.common.project.facet.core.xml.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.webProjectName}/.settings
file = org.eclipse.wst.common.project.facet.core.xml
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
