template = templates/jee1/glassfish-eclipse/settings/war/org.eclipse.wst.common.project.facet.core.xml.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/${project.alias}-war/.settings
file = org.eclipse.wst.common.project.facet.core.xml
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
