template = templates/jee1/setup/scripts/windows/ln-s.bat.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/windows
file = ln-s.bat
dollar.string = $
pound.string = #
absolute.string = C:
backslash.string = \\
separator.string = \\
