template = templates/jee1/setup/scripts/windows/variables-conf.bat.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/management/setup/scripts/windows
file = variables-conf.bat
dollar.string = $
pound.string = #
backslash.string = \\
