template = templates/jee1/jboss-eclipse/settings/resources/org.eclipse.wst.common.project.facet.core.xml.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.alias}-resources/.settings
file = org.eclipse.wst.common.project.facet.core.xml
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
