for-each = module.page
module.predicate = adalid.core.predicates.IsEnterpriseJavaWebModule
module.comparator = adalid.core.comparators.ByProjectName
page.predicate = adalid.core.predicates.IsProcessingDisplay
page.predicate = adalid.core.predicates.IsConsoleViewDisplay
page.comparator = adalid.core.comparators.ByDisplayName
template = templates/jee1/web/java/pages/SEP34.java.vm
path = ${warProjectFolderPath}/${webJavaSourcesFolder}
package = ${project.rootPackageName}.web.${module.wrapper.dottedAlias}.pages
file = $!{webPageNamePrefix}${page.name}.java
SelectOption.class = adalid.core.enums.SelectOption
SqlQualifierType.class = adalid.core.enums.SqlQualifierType
#
# packages
#
processPackage.string = ${project.rootPackageName}.ejb.business.process
entityPackage.string = ${project.rootPackageName}.ejb.persistence.entity
facadePackage.string = ${project.rootPackageName}.ejb.persistence.facade
