template = templates/jee1/base/source/jee1ap101/jee1ap101-ejb/eclipse.settings/org.eclipse.wst.common.component
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.ejbProjectName}/.settings
file = org.eclipse.wst.common.component
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
