disabled = true
for-each = sqlFolder
template = templates/database/postgresql/concat-sql.bat.vm
path = ${managementFolderPath}/resources/database/postgresql
file = concat-${sqlFolder}.bat
execute-command = cmd /c "$fileName"
execute-directory = $filePath
FilUtils.class = adalid.commons.util.FilUtils
targetFolder.string = ${managementFolderPath}/sql/postgresql
