template = templates/database/postgresql/create-trigger-function.vm
path = ${managementFolderPath}/sql/postgresql
file = create-trigger-function.sql
DatabaseTriggerType.class = adalid.core.enums.DatabaseTriggerType
