template = templates/database/postgresql/drop-trigger-function.vm
path = ${managementFolderPath}/sql/postgresql
file = drop-trigger-function.sql
DatabaseTriggerType.class = adalid.core.enums.DatabaseTriggerType
