template = templates/jee1/glassfish-eclipse/project/war/eclipse.classpath.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.alias}-war
file = .classpath
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
