disabled = true
template = templates/meta/sql/postgresql/alter.vm
# path = ${rootFolderSlashedPath}/${merger.newSchema}/source/management/resources/database/postgresql/data-migration
# package = base
path = test
package = meta.sql.postgresql
file = alter-${merger.oldSchema}-${merger.newSchema}.sql
