template = templates/meta/sql/postgresql/copy.vm
path = ${rootFolderSlashedPath}/${merger.projectAlias}/source/management/resources/database/${merger.dbms}/data-migration/base
file = copy-${merger.oldSchema}-${buildDate}.sql
