template = templates/meta/sql/postgresql/copy.vm
# path = ${rootFolderSlashedPath}/${merger.newSchema}/source/management/resources/database/postgresql/data-migration
# package = base
path = test
package = meta.sql.postgresql
file = copy-${merger.oldSchema}-${buildDate}.sql
