template = templates/meta/sql/postgresql/migrate.vm
path = ${rootFolderSlashedPath}/${merger.projectAlias}/source/management/resources/database/${merger.dbms}/data-migration/base
file = migrate-${merger.oldSchema}-${buildDate}.sql
