template = templates/meta/sql/postgresql/migrate.vm
# path = ${rootFolderSlashedPath}/${merger.newSchema}/source/management/resources/database/postgresql/data-migration
# package = base
path = test
package = meta.sql.postgresql
file = migrate-${merger.oldSchema}-${merger.newSchema}-${buildDate}.sql
