# Las propiedades velocity.template.encoding especifican la codificacion de caracteres de plantillas con una extension especifica.
# El valor por omision es ISO-8859-1. Se puede utilizar una codificacion alternativa, como UTF-8.
# Para utilizar una codificacion alternativa para plantillas con una extension especifica, agregue la propiedad correspondiente aqui.
# Por ejemplo, agregue velocity.template.encoding.java=UTF-8 para decodificar las plantillas con extension .java con UTF-8.
#
#
# Las propiedades velocity.document.encoding especifican la codificacion de caracteres de documentos generados con una extension especifica.
# El valor por omision es ISO-8859-1. Se puede utilizar una codificacion alternativa, como UTF-8.
# Para utilizar una codificacion alternativa para documentos generados con una extension especifica, agregue la propiedad correspondiente aqui.
# Por ejemplo, agregue velocity.document.encoding.java=UTF-8 para codificar los documentos generados con extension .java con UTF-8.
#
velocity.document.encoding.classpath=UTF-8
velocity.document.encoding.component=UTF-8
velocity.document.encoding.java=UTF-8
velocity.document.encoding.jrtx=UTF-8
velocity.document.encoding.jrxml=UTF-8
velocity.document.encoding.jsp=UTF-8
velocity.document.encoding.jspf=UTF-8
velocity.document.encoding.project=UTF-8
velocity.document.encoding.tld=UTF-8
velocity.document.encoding.xhtml=UTF-8
velocity.document.encoding.xml=UTF-8
