# Velocity Configuration Keys and Values
# http://velocity.apache.org/engine/releases/velocity-1.7/developer-guide.html
#
runtime.log.logsystem.class = org.apache.velocity.runtime.log.Log4JLogChute
runtime.log.logsystem.log4j.logger = adalid.commons.velocity.VelocityEngineer
file.resource.loader.description = Custom Velocity File Resource Loader
file.resource.loader.class = adalid.commons.velocity.VelocityFileResourceLoader
file.resource.loader.cache = true
velocimacro.library = macros/global-macros.vm
velocimacro.library.autoreload = true
velocimacro.permissions.allow.inline = true
velocimacro.permissions.allow.inline.local.scope = true
velocimacro.permissions.allow.inline.to.replace.global = true
directive.parse.max.depth = 15
#
# La propiedad input.encoding especifica la codificacion de caracteres (encoding) de las plantillas.
# El valor por omision es ISO-8859-1. Se puede utilizar una codificacion alternativa, como UTF-8.
# Tambien se puede utilizar una codificacion alternativa para plantillas con una extension especifica.
# Para ello, agregue la propiedad correspondiente al archivo velocity.supplementary.properties.
#
input.encoding = ISO-8859-1
#
# La propiedad output.encoding especifica la codificacion de caracteres (encoding) de los documentos generados.
# El valor por omision es ISO-8859-1. Se puede utilizar una codificacion alternativa, como UTF-8.
# Tambien se puede utilizar una codificacion alternativa para documentos generados con una extension especifica.
# Para ello, agregue la propiedad correspondiente al archivo velocity.supplementary.properties.
#
output.encoding = ISO-8859-1
