runtime.log.logsystem.class = org.apache.velocity.runtime.log.Log4JLogChute
runtime.log.logsystem.log4j.logger = adalid.commons.velocity.VelocityEngineer
file.resource.loader.description = Custom Velocity File Resource Loader
file.resource.loader.class = adalid.commons.velocity.VelocityFileResourceLoader
file.resource.loader.cache = true
velocimacro.library = macros/global-macros.vm
velocimacro.library.autoreload = true
velocimacro.permissions.allow.inline = true
velocimacro.permissions.allow.inline.local.scope = true
velocimacro.permissions.allow.inline.to.replace.global = true
directive.parse.max.depth = 15
