#
# document encodings
#
velocity.document.encoding.classpath=UTF-8
velocity.document.encoding.component=UTF-8
velocity.document.encoding.java=UTF-8
velocity.document.encoding.jrtx=UTF-8
velocity.document.encoding.jrxml=UTF-8
velocity.document.encoding.jsp=UTF-8
velocity.document.encoding.jspf=UTF-8
velocity.document.encoding.project=UTF-8
velocity.document.encoding.tld=UTF-8
velocity.document.encoding.xhtml=UTF-8
velocity.document.encoding.xml=UTF-8
