template = templates/jee1/base/source/jee1ap101/jee1ap101-ejb/eclipse.project
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.ejbProjectName}
file = .project
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
