file.resource.loader.path = meta/platform/sql

Bundle.class = adalid.commons.bundles.Bundle
ColUtils.class = adalid.commons.util.ColUtils
ComparatorUtils.class = org.apache.commons.collections.ComparatorUtils
PredicateUtils.class = org.apache.commons.collections.PredicateUtils
Sequence.class = adalid.commons.util.Sequence
