file.resource.loader.path = jee1/postgresql
file.resource.loader.path = database/postgresql

Bundle.class = adalid.commons.bundles.Bundle
ColUtils.class = adalid.commons.util.ColUtils
ComparatorUtils.class = org.apache.commons.collections.ComparatorUtils
Constants.class = adalid.core.Constants
Operation.class = adalid.core.Operation
Sequence.class = adalid.commons.util.Sequence
PredicateUtils.class = org.apache.commons.collections.PredicateUtils

byDisplayName.instance = adalid.core.comparators.ByDisplayName
byEntityName.instance = adalid.core.comparators.ByEntityName
byOperationName.instance = adalid.core.comparators.ByOperationName
byProjectName.instance = adalid.core.comparators.ByProjectName
byProjectDeclaringFieldName.instance = adalid.core.comparators.ByProjectDeclaringFieldName

isEntitySqlCodeGenEnabled.instance = adalid.core.predicates.IsEntitySqlCodeGenEnabled
isPersistentEntity.instance = adalid.core.predicates.IsPersistentEntity
isPersistentEntityTable.instance = adalid.core.predicates.IsPersistentEntityTable
isPersistentEntityWithTable.instance = adalid.core.predicates.IsPersistentEntityWithTable
isPersistentEnumerationEntity.instance = adalid.core.predicates.IsPersistentEnumerationEntity

bundleProgrammer.programmer = adalid.core.programmers.ResourceBundleProgrammer
javaProgrammer.programmer = adalid.core.programmers.JDK7Programmer
sqlProgrammer.programmer = adalid.core.programmers.PostgreSqlProgrammer

SqlQualifierType.class = adalid.core.enums.SqlQualifierType

isBidirectionalEntityReference.instance = adalid.core.predicates.IsBidirectionalEntityReference
isUnidirectionalEntityReference.instance = adalid.core.predicates.IsUnidirectionalEntityReference

isAccesibleOperation.instance = adalid.core.predicates.IsAccesibleOperation
isAccesibleOperationInEntity.instance = adalid.core.predicates.IsAccesibleOperationInEntity

isBasicDatabaseOperation.instance = adalid.core.predicates.IsBasicDatabaseOperation

isExportOperation.instance = adalid.core.predicates.IsExportOperation
isExportOperationInEntity.instance = adalid.core.predicates.IsExportOperationInEntity

isReportOperation.instance = adalid.core.predicates.IsReportOperation
isReportOperationInEntity.instance = adalid.core.predicates.IsReportOperationInEntity

isProcedureOperation.instance = adalid.core.predicates.IsProcedureOperation
isProcedureOperationInEntity.instance = adalid.core.predicates.IsProcedureOperationInEntity

isProcessOperation.instance = adalid.core.predicates.IsProcessOperation
isProcessOperationInEntity.instance = adalid.core.predicates.IsProcessOperationInEntity

isSimpleOperation.instance=adalid.core.predicates.IsSimpleOperation

isConsoleViewDisplay.instance = adalid.core.predicates.IsConsoleViewDisplay
isProcessingDisplay.instance = adalid.core.predicates.IsProcessingDisplay
isTableViewDisplay.instance = adalid.core.predicates.IsTableViewDisplay

isMenuModule.instance =  adalid.core.predicates.IsMenuModule
isRoleModule.instance =  adalid.core.predicates.IsRoleModule
isWebModule.instance =  adalid.core.predicates.IsEnterpriseJavaWebModule

targetApplicationServer.string = GlassFish
targetDatabaseServer.string=PostgreSQL

earProjectFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}
earConfigurationFilesFolder.string=src/conf

ejbProjectFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.ejbProjectName}
ejbConfigurationFilesFolder.string=src/conf
ejbServerResourcesFolder.string=setup
ejbJavaSourcesFolder.string=src/java/crop
ejbJavaTestFolder.string=test

warProjectFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.webProjectName}
warConfigurationFilesFolder.string=src/conf
webConfigurationFilesFolder.string=web/WEB-INF
webJavaSourcesFolder.string=src/java/crop
webPagesFolder.string=web

libProjectFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.libProjectName}
libJavaSourcesFolder.string=src/java/crop

resourcesProjectFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.resourcesProjectName}
resourcesBundlesFolder.string=src/crop

managementFolderPath.string=${rootFolderSlashedPath}/${project.baseFolderName}/source/management
