template = templates/jee1/jboss-eclipse/settings/war/org.eclipse.wst.common.project.facet.core.prefs.xml.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.alias}-war/.settings
file = org.eclipse.wst.common.project.facet.core.prefs.xml
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
