template = templates/jee1/resources/config/linux/project.properties.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/resources/config/linux
file = ${project.alias}.properties
dollar.string = $
pound.string = #
backslash.string = \\
