#setGlobalVariables()
template = templates/database/postgresql/util/insert-select-past-data.vm
path = ${managementFolderPath}/resources/database/postgresql/data-migration/base
file = insert-select-past-data-${implementationVersionStamp}.sql
