template = templates/jee1/ejb/business/java/BusinessProcessBrokerBean.java.vm
path = ${ejbProjectFolderPath}/${ejbJavaSourcesFolder}
package = ${project.rootPackageName}.ejb.business.jms
file = BusinessProcessBrokerBean.java
messagePackage.string = ${project.rootPackageName}.ejb.business.message
processPackage.string = ${project.rootPackageName}.ejb.business.process
processLogicPackage.string = ${project.rootPackageName}.ejb.business.process.logic
entityPackage.string = ${project.rootPackageName}.ejb.persistence.entity
facadePackage.string = ${project.rootPackageName}.ejb.persistence.facade
baseEntityConstantPackage.string = ${project.rootPackageName}.lib.base.entity.constant
