for-each = entity
entity.getter = getEntitiesList
entity.predicate = adalid.core.predicates.IsProcessOperationInEntity
entity.predicate = adalid.core.predicates.IsPersistentEntity
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/ejb/business/java/EntityBusinessProcessLogicImpl.java.vm
path = ${ejbProjectFolderPath}/${ejbJavaTestFolder}
package = ${project.rootPackageName}.ejb.business.process.logic.impl
file = ${entity.wrapper.javaClassName}BusinessProcessLogicImpl.java
messagePackage.string = ${project.rootPackageName}.ejb.business.message
processPackage.string = ${project.rootPackageName}.ejb.business.process
processLogicPackage.string = ${project.rootPackageName}.ejb.business.process.logic
entityPackage.string = ${project.rootPackageName}.ejb.persistence.entity
facadePackage.string = ${project.rootPackageName}.ejb.persistence.facade
baseEntityConstantPackage.string = ${project.rootPackageName}.lib.base.entity.constant
prototypeSetters.string = true
