template = templates/jee1/jboss-eclipse/project/war/eclipse.classpath.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.webProjectName}
file = .classpath
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
