template = templates/jee1/base/source/jee1ap101/jee1ap101-resources/eclipse.settings/org.eclipse.jdt.core.prefs
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/${project.alias}-resources/.settings
file = org.eclipse.jdt.core.prefs
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
