template = templates/meta/folder/csv/meta-folder-1.vm
path = ${rootFolderSlashedPath}/adalid/source/documents/csv
file = containers.csv
FileBytesSize.class = adalid.util.io.FileBytesSize
FileLinesSize.class = adalid.util.io.FileLinesSize
