template = templates/jee1/jboss-eclipse/settings/org.eclipse.wst.common.project.facet.core.xml.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/.settings
file = org.eclipse.wst.common.project.facet.core.xml
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
