for-each = entity
entity.predicate = adalid.core.predicates.IsPersistentEntityWithDisplay
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/web/java/commons/assistants/AsistentePaginaActualizacion.java.vm
path = ${warProjectFolderPath}/${webJavaSourcesFolder}
package = ${project.rootPackageName}.web.commons.assistants
file = AsistentePaginaActualizacion${entity.wrapper.javaClassName}.java
SqlQualifierType.class = adalid.core.enums.SqlQualifierType
