template = templates/jee1/jboss-eclipse/project/resources/eclipse.classpath.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/${project.alias}-resources
file = .classpath
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
