for-each = entity
entity.getter = getEntitiesList
entity.predicate = adalid.core.predicates.IsExplicitlyDeclaredEntity
entity.predicate = adalid.core.predicates.IsPersistentEntity
entity.not.predicate = adalid.core.predicates.IsPersistentEnumerationEntity
entity.predicate.join = all
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/resources/reporting/jasper/entity.jrxml.vm
path = ${managementFolderPath}/resources/reporting
package = jasper/reports/entity-list
file = ${entity.wrapper.sqlSchemaQualifiedShortName}.jrxml
