template = templates/jee1/glassfish-eclipse/project/ejb/eclipse.classpath.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.ejbProjectName}
file = .classpath
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
