template = templates/jee1/jboss-netbeans/ant/ejb/build.xml.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/${project.ejbProjectName}
file = build-for-windows.xml
dollar.string = $
pound.string = #
absolute.string = C:
backslash.string = \\
separator.string = \\
