template = templates/jee1/jboss-postgresql/setup/scripts/windows/variables-home.bat.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/windows
file = variables-home.bat
dollar.string = $
pound.string = #
backslash.string = \\
