disabled = true
for-each = entity
entity.getter = getEntitiesList
entity.predicate = adalid.core.predicates.IsExplicitlyDeclaredEntity
entity.predicate = adalid.core.predicates.IsPersistentEntityWithTable
entity.predicate.join = all
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/postgresql/views/create-jasper-report-view.sql.vm
path = ${managementFolderPath}/resources/database/postgresql
package = views/jasper-report
file = ${entity.wrapper.sqlSchemaQualifiedShortName}.sql
