for-each = entity
entity.getter = getEntitiesList
entity.predicate = adalid.core.predicates.IsPersistentEntityWithTable
entity.predicate.join = all
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/postgresql/views/create-data-provider-view.sql.vm
path = ${managementFolderPath}/resources/database/postgresql
package = views/data-provider
file = ${entity.wrapper.sqlName}.sql
SelectOption.class = adalid.core.enums.SelectOption
VirtualEntityType.class = adalid.core.enums.VirtualEntityType
