template = templates/jee1/jboss-eclipse/ant/ejb/weaving.xml.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/${project.alias}-ejb
file = weaving-for-linux.xml
dollar.string = $
pound.string = #
absolute.string = /opt
backslash.string = \\
separator.string = /
