template = templates/jee1/resources/config/windows/project.properties.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/resources/config/windows
file = ${project.alias}.properties
dollar.string = $
pound.string = #
backslash.string = \\
