for-each = entity
entity.predicate = adalid.core.predicates.IsPersistentEntityWithDisplay
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/web/java/commons/interfaces/PaginaActualizacion.java.vm
path = ${warProjectFolderPath}/${webJavaSourcesFolder}
package = ${project.rootPackageName}.web.commons.interfaces
file = PaginaActualizacion${entity.wrapper.javaClassName}.java
