template = templates/jee1/jboss-postgresql/setup/scripts/linux/variables-home.sh.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/linux
file = variables-home.sh
dollar.string = $
pound.string = #
absolute.string = /opt
backslash.string = \\
separator.string = /
