template = templates/jee1/glassfish/conf/glassfish-application.xml.vm
path = ${earProjectFolderPath}/${earConfigurationFilesFolder}
file = glassfish-application.xml
TipoRol.class = meta.entidad.comun.control.acceso.TipoRol
