set xf=/xf
set xf=%xf% Thumbs.db
set xf=%xf% *.lnk
set xf=%xf% *.log
set xd=/xd
set xd=%xd% %~f1\release
set xd=%xd% %~f1\source\jee1ap101\jee1ap101-war\build\web\resources
rem xd=%xd% %~f1\source\management\resources\reporting\jasper\reports\custom-made
rem xd=%xd% %~f1\source\management\resources\reporting\jasper\reports\entity-list
rem xd=%xd% %~f1\source\management\resources\reporting\jasper\reports\user-defined
set xd=%xd% build
set xd=%xd% dist
