template = templates/jee1/glassfish-postgresql/setup/scripts/linux/ln-s.sh.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/linux
file = ln-s.sh
dollar.string = $
pound.string = #
backslash.string = \\
