template = templates/jee1/glassfish-postgresql/setup/scripts/linux/variables-home.sh.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/linux
file = variables-home.sh
dollar.string = $
pound.string = #
backslash.string = \\
