template = templates/jee1/jboss-netbeans/ant/ejb/build.xml.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/${project.alias}/${project.alias}-ejb
file = build-for-linux.xml
dollar.string = $
pound.string = #
absolute.string = /opt
backslash.string = /
