template = templates/jee1/setup/scripts/linux/ln-s.sh.vm
path = ${rootFolderSlashedPath}/${project.alias}/source/management/setup/scripts/linux
file = ln-s.sh
dollar.string = $
pound.string = #
absolute.string = /opt
backslash.string = \\
separator.string = /
