template = templates/jee1/setup/scripts/linux/variables-conf.sh.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/management/setup/scripts/linux
file = variables-conf.sh
dollar.string = $
pound.string = #
backslash.string = \\
