for-each = entity
entity.getter = getEntitiesList
entity.predicate = adalid.core.predicates.IsPersistentEntity
entity.comparator = adalid.core.comparators.ByEntityName
template = templates/jee1/ejb/persistence/java/EntityFacadeLocal.java.vm
path = ${ejbProjectFolderPath}/${ejbJavaSourcesFolder}
package = ${project.rootPackageName}.ejb.persistence.facade
file = ${entity.wrapper.javaClassName}FacadeLocal.java
baseEntityPackage.string = ${project.rootPackageName}.lib.base.persistence.entity
baseFacadePackage.string = ${project.rootPackageName}.lib.base.persistence.facade
entityPackage.string = ${project.rootPackageName}.ejb.persistence.entity
facadePackage.string = ${project.rootPackageName}.ejb.persistence.facade
