template = templates/meta/java/sql/jee1-module.vm
path = ${reader.metajavaPath}
package = ${reader.targetMetajavaPackage}
file = Modulo1.java
entitiesPackage.string = ${reader.targetMetajavaPackage}.entities
byTableName.instance = adalid.util.sql.ByTableName
isFairTable.instance = adalid.util.sql.IsFairTable
