template = templates/meta/java/sql/jee1-master.vm
path = ${reader.metajavaPath}
package = ${reader.targetMetajavaPackage}
file = Maestro.java
entitiesPackage.string = ${reader.targetMetajavaPackage}.entities
