for-each = table
table.predicate = adalid.util.sql.IsRootTable
template = templates/meta/java/sql/persistent-discriminator-entity.vm
path = ${reader.metajavaPath}
package = ${reader.targetMetajavaPackage}.entities
file = Discriminador${table.capitalizedJavaName}.java
