for-each = module.page
module.predicate = adalid.core.predicates.IsEnterpriseJavaWebModule
module.comparator = adalid.core.comparators.ByProjectName
page.predicate = adalid.core.predicates.IsReadingDisplay
page.predicate = adalid.core.predicates.IsTableViewDisplay
page.not.predicate = adalid.core.predicates.IsMasterDetailDisplay
page.comparator = adalid.core.comparators.ByDisplayName
template = templates/jee1/web/jsp/pages/SEP11.jsp.vm
path = ${warProjectFolderPath}/${webPagesFolder}/crop/${module.wrapper.dottedAlias.replace('.', '/')}
file = $!{webPageNamePrefix}${page.name}.jsp
