template = templates/jee1/glassfish-eclipse/settings/org.eclipse.wst.common.component.vm
path = ${rootFolderSlashedPath}/${project.baseFolderName}/source/${project.rootFolderName}/.settings
file = org.eclipse.wst.common.component
preserve = true
dollar.string = $
pound.string = #
backslash.string = \\
